### ISSUE TITLE
Error parsing string into Single

### ISSUE THREAD

**Issue by moukrea** [Tamk1s/Thwimp#11]
Whenever I try to launch it, I got the "Data file parsing/I/O error!
Error parsing string into Single" alert popping up...

Therefore, even if I set everytrhing properly, I can't use the program at all, the THP tab doesn't work (only displays 0 in all areas, except description)

Here's the log:

`MsgBox:
title: Data file parsing/ I/O error!
msg: Error parsing string into Single
icon: DefaultButton1, OkOnly, Critical`

**Comment by Tamk1s** [comment]
It sounds like an error is occurring on boot of Thwimp, when it is reading the data files (in InitTHPData func), which drives most of the application's functionality in the THP tab. Specifically, the parsing of the THP FPS string value from FileData.txt file into a "single" VisualBasic datatype value (aka 2-digit decimal value) is failing. The parsing is done via a function call to TryParseErr_Single() func at line 299 in the application.

Since a parse conversion failure occurs and the error gets caught, InitTHPData function halts, and the application doesn't work, due to inability to load all THP database data needed (hence all zeroes appearing in the THP tab.)


**Workarounds/fixes:**

Make sure valid data files (FileListing.txt, FileCDesc.txt, FileData.txt, and FileDesc.txt, included as default files for MKWii in the latest build archive) exist in the **same directory** as Thwimp executable on boot, and with valid data. That directory with Thwimp should have read/write access. See the breakdown of the structure for those data files [here](https://github.com/Tamk1s/Thwimp#4-customization). Do note the last few builds have been WIP pre-release, and the manual is somewhat outdated (see the release notes for updates with these builds); however, that Customization section in the manual is still valid and up-to-date. Manual to be updated with v1.2 final build release, which should be arriving around end of week/early next week, with CLI feature added.

If using and creating custom data files for other games, the FPS value is the 14th comma-delimited entry for each line in FileData.txt, where each line corresponds to a THP file (from FileListing.txt); see info in that breakdown link. It should be a valid, numeric single value (such as 12.34, 50 for MKWii PAL video files, 59.94 MKWii NTSC files, etc.)


**Bugs found by me related to this issue:**
- DataFile Dir path (path to where the data files exist to read from) in Options tab is initalized to the current Thwimp executable directory **on boot**
- InitTHPData() func is **only** called to load the data files' information **on application boot**, using the current DataFile Dir (which is initialized to current Thwimp executable path). Meaning if that current directory isn't accessible or found on boot, errors would occur.
- DataFile Dir path in Options tab does **not** reload the THP data into memory (no other calls to InitTHPData). Meaning that functionality is currently broken.


**Bugfixes for me to make for incoming v1.2 Final build release:**
- Do not initialize DataFile Dir path on application boot; set the DataFile Dir OpenFileDialog box to start at the application's current directory, and make the user define the DataFile Dir path every time (or load it from settings INI file)
- Make setting the DataFile Dir path from the OpenFileDialog box call InitTHPData function, in order to reload the data files from there.
- Tweak InitTHPData function to use the DataFile Dir path for reading the database text files.


For now, you should place valid data files into the Thwimp directory (directory should have read/write and probably admin access), whether they be default or custom, due to the DataFile Dir feature not working.

**Comment by moukrea** [comment]
Wow that's a really detailled answer, thanks!

Did a little investigation, it appears that if I set all FPS values at 50, the parsing I/O error vanishes but playback fails, however if I set one of the file FPS value to 59.94, the parsing I/O error pops back, but I can play the said file (haven't yet tried to rip though)

**Comment by Tamk1s** [comment]
This might be a stretch, but could you report back with the following [**Regional Settings**](https://resrequest.helpspot.com/index.php?pg=kb.page&id=279) for your machine:
- Regional Format (in "Formats" tab)
- Decimal Symbol
- List Separator


**Probable bug cause:**

Due to how THP Data is defined, the application and default data files expect to parse single values by using a dot (.) for the decimal symbol, a comma (,) for list separation of items in the data files, and a semicolon (;) at the end of a line to define a THP. Specifically, it is setup for "English (United States)" regional format. What is probably happening is your machine could be setup on your end in a foreign regional format, such as comma (,) and dot (.) for decimal symbol and list separator, respectively. This would result in strings such as "12,34" needed for a proper Single, instead of expected "12.34"  .

The application is hardcoded to fetch substring entries on each line within the THP Data file (FileData.txt) between commas, where each line is defined as 18 entries and ends with a semicolon. It then parses those substrings into the appropriate data type based on the target variable type from that breakdown manual page from before. For Single parsing for FPS, it uses [TryParse(String, Single) .NET method](https://docs.microsoft.com/en-us/dotnet/api/system.single.tryparse?view=netcore-3.1#System_Single_TryParse_System_String_System_Single__), which uses the machine's **current Regional Setting**. That was an oversight on my part, and is most likely the bug cause.

If so on using a foreign Region Setting, that may explain the Single parsing error, with the parsing sometimes working, other times not. It successfully converts the FPS string "50" to Single, because there are no decimal symbols of any kind to handle, but it fails on decimal values such as "59.94" because the regional settings for your machine was expecting to find "59,94" for that value. Of course, if you were to actually use a value of "59,94" FPS in the data files with that Regional Setting, that would break reading the THP data from the files, since it is hardcoded to find substrings between commas and then parse them appropriately into data types. (The extra comma in that FPS value would misalign data reading.)


**Workaround:**

If this is indeed the bug cause, temporarily changing the Regional Settings as such when using the application would workaround the bug:
- Regional Format = English (United States)
- Decimal Symbol = . (dot)
- List Separator = , (comma)

You may need to restart the machine for the effects to take place. Let me know if that fixes things up!


**Bugfix on my end to make for v1.2 Final:**
- Change my TryParseErr_Single() wrapper function to parse single values using an overload of Single.TryParse method that is forced into English (United States) format. (Dot (.) for decimal symbol). This will fix the problem, as well as prevent the need to have separate data file sets for different regions.

**Comment by Tamk1s** [comment]
@Moukrea Hello! Sorry for the delay on this, but I've just pushed a [newer build (v1.2c)](https://github.com/Tamk1s/Thwimp/releases/tag/v1.2c) to fix the various issues discussed in this bug thread. (DataFile directory bugs, and the Single parsing.)

Let me know if this fixes the culture bug when reading the FPS data.
